apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lease-frontend2
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: lease-frontend2
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: lease-frontend2
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: ssh://git@github.com/Mpluya/tshoot-node-buildpack?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/is-prometheus-enabled-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: lease-frontend2
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: lease-frontend2
    spec:
      containers:
      - image: cxscssa.azurecr.io/tap-build/workloads/lease-frontend2-mae@sha256:dab39b73b4e950b121a733a5333fced2434020f2ed1d66ce284df368eaf53dc0
        name: workload
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

