apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: appsso-starter-java
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/workload-type: web
    autoscaling.knative.dev/min-scale: "1"
    app.kubernetes.io/component: run
    carto.run/workload-name: appsso-starter-java
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/x95castle1/appsso-starter-java?sub_path=/
        boot.spring.io/version: 3.0.4
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/is-prometheus-enabled-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"appsso-starter-java","apps.tanzu.vmware.com/workload-type":"web","autoscaling.knative.dev/min-scale":"1"},"name":"appsso-starter-java","namespace":"jeremy"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"serviceClaims":[{"name":"appsso-starter-java-for-auth0","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"appsso-starter-java-for-auth0"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/x95castle1/appsso-starter-java"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: appsso-starter-java
        apps.tanzu.vmware.com/workload-type: web
        autoscaling.knative.dev/min-scale: "1"
        carto.run/workload-name: appsso-starter-java
        conventions.carto.run/framework: spring-boot
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: cxscssa.azurecr.io/tap-build/workloads/appsso-starter-java-jeremy@sha256:e7fe3f81033895e95ac663968687e002d5c72dc5c51655178454b9cc7b2d06dd
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway

