apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: carvel-web-workload.dev2.cssa.vmware.com.20240724204604.0.0
  labels:
    app.kubernetes.io/part-of: carvel-web-workload
spec:
  refName: carvel-web-workload.dev2.cssa.vmware.com
  version: 20240724204604.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: cxscssa.azurecr.io/tap-build/workloads/carvel-web-workload-dev2-bundle@sha256:b8b951b4a18b0ba99998293b4a55da6139a8aecf9909870e668fbe8709cff316
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

