apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: friday-sre-package.bobbyhana.cssa.vmware.com.20240718155332.0.0
  labels:
    app.kubernetes.io/part-of: friday-sre-package
spec:
  refName: friday-sre-package.bobbyhana.cssa.vmware.com
  version: 20240718155332.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: cxscssa.azurecr.io/tap-build/workloads/friday-sre-package-bobbyhana-bundle@sha256:4607b3a6c627d7e561cf908d7a9668fee6c050904648330c5329c4af8b6fd581
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

