apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: friday-sre-package.bobbyhana.cssa.vmware.com.20240719230224.0.0
  labels:
    app.kubernetes.io/part-of: friday-sre-package
spec:
  refName: friday-sre-package.bobbyhana.cssa.vmware.com
  version: 20240719230224.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: cxscssa.azurecr.io/tap-build/workloads/friday-sre-package-bobbyhana-bundle@sha256:75b2606876d310150afddc612978500d478e22e1ea04bc460540c17c3e1e9847
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

