apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: friday-sre-package.bobbyhana.cssa.vmware.com.20240724205009.0.0
  labels:
    app.kubernetes.io/part-of: friday-sre-package
spec:
  refName: friday-sre-package.bobbyhana.cssa.vmware.com
  version: 20240724205009.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: cxscssa.azurecr.io/tap-build/workloads/friday-sre-package-bobbyhana-bundle@sha256:0582ddc4a7aa56c4f908f78725c17c5c8c432869334cba0efb900b0bed81a511
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

