apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-image-package
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: petclinic-image-package
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: petclinic-image-package
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: petclinic-image-package
      apps.tanzu.vmware.com/carvel-package-workflow: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: petclinic-image-package
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: springcommunity/spring-framework-petclinic
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: petclinic-image-package
        apps.tanzu.vmware.com/carvel-package-workflow: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: petclinic-image-package
    spec:
      containers:
      - image: index.docker.io/springcommunity/spring-framework-petclinic@sha256:2766c68b03afd64d154339a2574cdf18db1a1b92b3013a4d6a3dfb9be1bac6cd
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-image-package
  labels:
    app.kubernetes.io/part-of: petclinic-image-package
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: petclinic-image-package
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: petclinic-image-package
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: petclinic-image-package
  ports:
  - targetPort: 8080
    port: 8080
    name: http

