---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: petclinic-image-package
 namespace: mae
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 packageRef:
   refName: petclinic-image-package.mae.cssa.vmware.com # name of the Package
   versionSelection:
     constraints: "20240129120702.0.0" # version of the Package
 values:
 - secretRef:
     name: petclinic-image-package-values