apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-java-web-app.pve.vmware.com-pkgi
spec:
  packageRef:
    refName: tanzu-java-web-app.pve.vmware.com
    versionSelection:
      constraints: 20240404202700.0.0+build.40b72170d6f12d508741276c138bb85065adfc95
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: tanzu-java-web-app
