apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-java-web-app.pve.vmware.com-pkgi
spec:
  packageRef:
    refName: tanzu-java-web-app.pve.vmware.com
    versionSelection:
      constraints: 20240724211929.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: tanzu-java-web-app.pve.vmware.com-values
