apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-statefulset-app.pve.vmware.com.20240411142614.0.0+build.40b72170d6f12d508741276c138bb85065adfc95
spec:
  refName: tanzu-java-statefulset-app.pve.vmware.com
  version: 20240411142614.0.0+build.40b72170d6f12d508741276c138bb85065adfc95
  releaseNotes: |
    Release v20240411142614.0.0+build.40b72170d6f12d508741276c138bb85065adfc95 of package tanzu-java-statefulset-app.pve.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: cxscssa.azurecr.io/tap-build/workloads/tanzu-java-statefulset-app-bundle@sha256:f3797c3e0f6abdfdd581e568872090135347b0e4bc1e1a26c78e51b6a8899b89
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      nullable: true
      default: null
