apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-java-statefulset-app.pve.vmware.com-pkgi
spec:
  packageRef:
    refName: tanzu-java-statefulset-app.pve.vmware.com
    versionSelection:
      constraints: 20240422140526.0.0+build.e3dccadaebb225732b2d8686f7b1af2878770e19
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: tanzu-java-statefulset-app
