apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-java-statefulset-app.pve.vmware.com-pkgi
spec:
  packageRef:
    refName: tanzu-java-statefulset-app.pve.vmware.com
    versionSelection:
      constraints: 20240422145515.0.0+build.c3bdf908e1cc6cfef4d71a37ac96866bfa9eb026
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: tanzu-java-statefulset-app
