apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: angular-frontend
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: angular-frontend
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: angular-frontend
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/Mpluya/angular-frontend?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: angular-frontend
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: angular-frontend
    spec:
      containers:
      - env:
        - name: api_backend
          value: http://java-rest-service-azure.mae.svc
        image: cxscssa.azurecr.io/tap-build/workloads/angular-frontend-mae@sha256:0dc61d141262e46b7570a3b506fbb2de3259a42b991e3e7d91336f3920b5f1aa
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

