apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: greeter-source-canary-sample-package.dev2.cssa.vmware.com.20240301131831.0.0
spec:
  refName: greeter-source-canary-sample-package.dev2.cssa.vmware.com
  version: 20240301131831.0.0
  releaseNotes: |
    Release v20240301131831.0.0 of package greeter-source-canary-sample-package.dev2.cssa.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: cxscssa.azurecr.io/tap-build/workloads/greeter-source-canary-sample-package-dev2-bundle@sha256:754ea919b5459366428303562d5513e382c4711f80cb83081185557114fc3e40
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          description: Required. Name of the workload, used by K8s Ingress HTTP rules.
          default: ""
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 1
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: letsencrypt-production

