apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: greeter-source-canary-sample-package.dev2.cssa.vmware.com.20240708191135.0.0
  labels:
    app.kubernetes.io/part-of: greeter-source-canary-sample-package
spec:
  refName: greeter-source-canary-sample-package.dev2.cssa.vmware.com
  version: 20240708191135.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: cxscssa.azurecr.io/tap-build/workloads/greeter-source-canary-sample-package-dev2-bundle@sha256:3a704ada1fc8da01fecca535afb739ac231224bb1a874ca48f559a506e2f4b14
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          default: ""
          minLength: 1
        replicas:
          title: Replicas
          type: integer
          default: 1
        port:
          title: Port
          type: integer
          default: 8080
        hostname:
          title: Hostname
          type: string
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          default: tap-ingress-selfsigned
        http_route:
          type: object
          additionalProperties: false
          nullable: true
          properties:
            gateways:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  protocol:
                    type: string
                    default: ""
                  name:
                    type: string
                    default: ""
              default:
              - protocol: https
                name: default-gateway

