---
apiVersion: v1
kind: Secret
metadata:
  name: friday-sre-package-values
stringData:
  values.yml: |
    ---
    workload_name: friday-sre-package
    replicas: 6
    pdb:
      enabled: true
    hostname: friday-sre-package.bobbyhana.run-prod.cssa.tapsme.org
    cluster_issuer: letsencrypt-production
