---
apiVersion: v1
kind: Secret
metadata:
  name: friday-sre-app
stringData:
  values.yml: |
    ---
    workload_name: friday-sre-app
    replicas: 4
    pdb:
      enabled: true
    hostname: friday-sre-app.bobbyhana.run-prod.cssa.tapsme.org
