apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-golang-kaniko
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: app-golang-kaniko
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: app-golang-kaniko
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/Mpluya/app-golang-kaniko?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: app-golang-kaniko
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: app-golang-kaniko
    spec:
      containers:
      - image: cxscssa.azurecr.io/tap-build/workloads/app-golang-kaniko-mae@sha256:85d3e697d40799e18eaaa7a0100cbd8d6fd53cbf0295d6ffb1ccb31c04a463e3
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

