apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: greeter-source-package.dev2.cssa.vmware.com.20230804120636.0.0
spec:
  refName: greeter-source-package.dev2.cssa.vmware.com
  version: 20230804120636.0.0
  releaseNotes: |
    Release v20230804120636.0.0 of package greeter-source-package.dev2.cssa.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.harbor.learn.tapsme.org/tap-build/workloads/greeter-source-package-dev2-bundle@sha256:a5728b59c119e8bfd5f2a95decb68143e9b6fc8a48c02c911330e16c268df097
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

