apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: greeter-source-package.dev2.cssa.vmware.com.20230804162126.0.0
spec:
  refName: greeter-source-package.dev2.cssa.vmware.com
  version: 20230804162126.0.0
  releaseNotes: |
    Release v20230804162126.0.0 of package greeter-source-package.dev2.cssa.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.harbor.learn.tapsme.org/tap-build/workloads/greeter-source-package-dev2-bundle@sha256:b09a68dcda006dc87874f4cf6dbd2c34d548e283ec38e05072d7a90fbb8e6e2c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

