apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tsc-app.pve.vmware.com-pkgi
spec:
  packageRef:
    refName: tsc-app.pve.vmware.com
    versionSelection:
      constraints: 20240724163632.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: tsc-app.pve.vmware.com-values
